version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test-short:
    desc: Run tests (short)
    cmds:
      - go test -short ./...

  coverage:
    desc: Generate test coverage report
    cmds:
      - go test -coverprofile=coverage ./...
      - go tool cover -func=coverage

  coverage-html:
    desc: Generate HTML test coverage report
    cmds:
      - go test -coverprofile=coverage ./...
      - go tool cover -html=coverage -o coverage.html
      - task: open-coverage

  open-coverage:
    desc: Open coverage report in browser
    cmds:
      - cmd: powershell -c "if (Test-Path coverage.html) { Invoke-Item coverage.html } else { Write-Error 'coverage.html not found' }"
        platforms: [windows]
      - cmd: open coverage.html
        platforms: [darwin]
      - cmd: xdg-open coverage.html
        platforms: [linux]

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  clean:
    desc: Clean build artifacts and coverage files
    cmds:
      - cmd: Remove-Item -Force coverage, coverage.html, dist -Recurse -ErrorAction SilentlyContinue
        platforms: [windows]
      - cmd: rm -f coverage coverage.html && rm -rf dist
        platforms: [linux, darwin]

  build:
    desc: Create a release build using GoReleaser
    cmds:
      - task: test
      - goreleaser build --snapshot --clean

  reseal:
    cmds:
      - go run main.go seal testdata/secret.yaml -o testdata/sealedsecret.yaml
      - go run main.go testdata/sealedsecret.yaml

  tag-release:
    desc: "Create and push a new version tag (use: task tag-release VERSION=v1.0.0)"
    requires:
      vars: [VERSION]
    vars:
      CURRENT_BRANCH:
        sh: git branch --show-current
    preconditions:
      - sh: '[ "{{.CURRENT_BRANCH}}" != "main" ]'
        msg: "Tags must be created from the main branch. Current branch: {{.CURRENT_BRANCH}}"
      - sh: "git fetch origin main"
        msg: "Fetching latest changes from origin/main"
      - sh: "git diff --quiet HEAD origin/main"
        msg: "Local main branch is not up to date with origin/main. Please pull latest changes."
    cmds:
      - 'echo "Creating and pushing tag {{.VERSION}} from main branch"'
      - git tag {{.VERSION}}
      - git push origin {{.VERSION}}
      - 'echo "Tag {{.VERSION}} created and pushed successfully"'

vars:
  EXE: '{{if eq OS "windows"}}.exe{{end}}'
